### ISSUE TITLE
let user prescribe body motion as a function. constraints on user?

### ISSUE THREAD

**Issue by ajgoza** [NUFgroup/IBPM.jl#14]

**Comment by jcallaham** [comment]
There is a bit of infrastructure for this with the MotionFunction and TangentSE2 types, but I don't know if there are currently any validated examples where this is actually used.

**Comment by ajgoza** [comment]
agreed, and I think these are useful starting points. I wonder if we can have a more general framework where the user can prescribe a motion function, perhaps as an array, like
motion = [ t->sin(5*t), t->0*t, ...]

where the first two entries are the x&y components of the velocity of the center of mass, and then perhaps the third is a radial velocity and the 4th and 5th are the coords of the center of rotation? I'm not sure of the exact form, but it would be slick (IMO) to have the user be able to provide more general motion and have the code take care of that under the hood
